### ISSUE TITLE
L'ajout du téléchargement a échoué

### ISSUE THREAD

**Issue by Bidouille28** [seansfkelley/synology-download-manager#170]
L'ajout du téléchargement a échoué
Erreur inopinée ; veuillez vérifier vos réglages et essayer à nouveau

Réglages OK

**********************************************************************
Redacted extension state: {
  "settings": {
    "connection": {
      "protocol": "http",
      "hostname": true,
      "port": true,
      "username": true,
      "password": true
    },
    "visibleTasks": {
      "downloading": true,
      "uploading": true,
      "completed": true,
      "errored": true,
      "other": true
    },
    "taskSortType": "name-asc",
    "notifications": {
      "enableFeedbackNotifications": true,
      "enableCompletionNotifications": false,
      "completionPollingInterval": 60
    },
    "shouldHandleDownloadLinks": true,
    "badgeDisplayType": "total"
  },
  "tasks": 4,
  "taskFetchFailureReason": null,
  "tasksLastInitiatedFetchTimestamp": 1611574280709,
  "tasksLastCompletedFetchTimestamp": 1611574280781,
  "lastSevereError": "(omitted for brevity)",
  "stateVersion": 5
}

error while trying to fetch metadata file type for download url

Error: 'Network Error'
Error stack trace: parcelRequire<.bIiH</module.exports@moz-extension://7b45cc46-7f00-4e52-8fda-6a9c40669d73/dist/background/index.js:228:87
parcelRequire<.KRuG</module.exports/</p.onerror@moz-extension://7b45cc46-7f00-4e52-8fda-6a9c40669d73/dist/background/index.js:238:1018

**Comment by seansfkelley** [comment]
Thanks for the bug report!

This is probably a problem with the site you're trying to download from or your connection to it. I just released a new version that should report something a little more useful in this case. Can you try it out and let me know what it says or if your issue is otherwise fixed? Do you see this problem on other downloads, or just this particular one/ones from this site?

**Comment by Bidouille28** [comment]
hello
configuration:
  - Firefox 85.0 (64) => extension V0.9.1
  - Chrome 88.0.4324.104 (Build officiel) (64 bits) => extension V0.9.0
  -  Opera 73.0.3856.344 => extension 2.2.13

Connection with nas ok

Download test on the same link

the extension works very well on opera but does not work on firefox and chrome

***************************************************
Chrome
**************************************************
Redacted extension state: {
  "lastSevereError": "(omitted for brevity)",
  "settings": {
    "badgeDisplayType": "total",
    "connection": {
      "hostname": true,
      "password": true,
      "port": true,
      "protocol": "http",
      "username": true
    },
    "notifications": {
      "completionPollingInterval": 60,
      "enableCompletionNotifications": true,
      "enableFeedbackNotifications": true
    },
    "shouldHandleDownloadLinks": true,
    "taskSortType": "name-asc",
    "visibleTasks": {
      "completed": true,
      "downloading": true,
      "errored": true,
      "other": true,
      "uploading": true
    }
  },
  "stateVersion": 5,
  "taskFetchFailureReason": null,
  "tasks": 3,
  "tasksLastCompletedFetchTimestamp": 1611835435800,
  "tasksLastInitiatedFetchTimestamp": 1611835435709
}

error while trying to fetch metadata file type for download url

Error: 'Network Error'
Error stack trace: Error: Network Error
    at module.exports (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/background/index.js:228:87)
    at XMLHttpRequest.p.onerror (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/background/index.js:238:1018)
**************************************************

**Comment by seansfkelley** [comment]
Thanks again for the information. There's been a little bit of confusion here.

The first bit of confusion is that I forgot to update the extension in the Chrome web store after I sent the message above, so you didn't see any change when you tried on Chrome again. Your Firefox has the latest version (0.9.1); can you try again there? It should provide a slightly more helpful error notification.

The other bit of confusion is that you seem to be using a different extension for Opera, as I don't recognize that version number.

I think there might be a change I can make here to improve the behavior. When you use the Opera extension with the problematic URL, do you end up with the correct file on your NAS, or do you end up with (for example) a `.torrent` file but not the actual content you want?

**Comment by seansfkelley** [comment]
Hi @Bidouille28, can you try out some of the stuff I mention i my previous comment and let me know if they fix it or provide more information?

**Comment by seansfkelley** [comment]
Ping @Bidouille28. Are you still having issues?

**Comment by seansfkelley** [comment]
Closing due to inactivity. The improved messaging and new FAQ entries cover the most likely culprits.
