### ISSUE TITLE
error when restarting browser

### ISSUE THREAD

**Issue by Careless** [seansfkelley/synology-download-manager#236]
```
Redacted extension state: {
  "settings": {
    "badgeDisplayType": "total",
    "connection": {
      "hostname": true,
      "password": true,
      "port": true,
      "rememberPassword": true,
      "username": true
    },
    "notifications": {
      "completionPollingInterval": 60,
      "enableCompletionNotifications": true,
      "enableFeedbackNotifications": true
    },
    "shouldHandleDownloadLinks": true,
    "showInactiveTasks": true,
    "taskSortType": "name-asc",
    "visibleTasks": {
      "completed": true,
      "downloading": true,
      "errored": true,
      "other": true,
      "uploading": true
    }
  },
  "stateVersion": 7,
  "taskFetchFailureReason": null,
  "tasks": 0,
  "tasksLastCompletedFetchTimestamp": 1702290896006,
  "tasksLastInitiatedFetchTimestamp": 1702290894744
}

TypeError: 'Cannot read properties of undefined (reading 'connection')'
Error stack trace: TypeError: Cannot read properties of undefined (reading 'connection')
    at r.UNSAFE_componentWillReceiveProps (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:515:2290)
    at Va (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:24:50461)
    at cu (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:24:70891)
    at hi (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:24:112748)
    at Gi (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:24:98864)
    at Yi (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:24:98792)
    at Ki (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:24:98655)
    at Vi (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:24:95523)
    at chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:24:45561
    at exports.unstable_runWithPriority (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:20:3932)

React stack trace:
    at r (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:515:828)
    at n (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/popup/index.js:63:729)
```

**Comment by seansfkelley** [comment]
Does this happen consistently when you open the browser, or only once? Can you provide the extension, browser, and DSM versions?

**Comment by Careless** [comment]
only happened once or twice. hasn't happened since. been operating well as it used to.

i am not sure what the cause for the error was, but i posted here in case it's something you should be aware of.

DSM 6.2, extension version 0.12.2 from chrome store, browser is Brave Version 1.61.104 / Chromium: 120.0.6099.115.

i didn't record the version number of the browser or extension when it happened so the version numbers may have incremented since.

seems ok now, though. not quite sure what triggered the error.

**Comment by seansfkelley** [comment]
Okay, got it, thanks for the heads up! If it was a transient issue, then I think there's nothing to be done. That code hasn't changed in years and isn't doing anything particularly weird, so I suspect it's just a very rare race condition.
